<?php

declare(strict_types=1);

namespace WorkOS\AuthKit\Install\Plans;

use Illuminate\Support\Facades\File;

class BreezeMigrationPlan extends BaseMigrationPlan
{
    #[\Override]
    public function generate(string $projectPath): string
    {
        $stack = $this->detectBreezeStack($projectPath);
        $databaseSection = $this->databaseMigrationSection();
        $userModelSection = $this->userModelSection();
        $envVarsSection = $this->envVarsSection();

        return <<<MARKDOWN
# Migration Plan: Laravel Breeze to WorkOS AuthKit

**Generated**: {$this->timestamp()}
**Detected Stack**: {$stack}
**Risk Level**: {$this->getRiskLevel()}

## Overview

You're migrating from Laravel Breeze ({$stack} stack) to WorkOS AuthKit. This guide provides step-by-step instructions for a safe migration.

WorkOS AuthKit replaces Breeze's local authentication with WorkOS-hosted authentication, which provides:
- Social logins (Google, Microsoft, GitHub, Apple)
- Magic link authentication
- Enterprise SSO
- Passkeys

## Pre-Migration Checklist

- [ ] Backup your database
- [ ] Create a WorkOS account at https://workos.com
- [ ] Test this migration in a staging environment first
- [ ] Review your User model for custom authentication logic

## Step 1: Files to Remove

These Breeze files are no longer needed:

### Controllers
{$this->listBreezeControllers($projectPath)}

### Views
{$this->listBreezeViews($projectPath)}

### Routes
- Remove or comment out auth routes in `routes/web.php` (Breeze routes)
- WorkOS AuthKit provides its own routes at `/auth/*`

## Step 2: Database Changes

{$databaseSection}

## Step 3: Update User Model

Add the WorkOS traits to your User model:

{$userModelSection}

## Step 4: Data Migration (Existing Users)

For existing users, you have two options:

### Option A: Users re-authenticate (Recommended)
Existing users will automatically be linked to their WorkOS identity when they first log in via WorkOS, matched by email address.

### Option B: Pre-link users via API
Use the WorkOS API to create users and store their workos_id before migration. See WorkOS User Management documentation.

## Step 5: Environment Variables

{$envVarsSection}

## Step 6: Remove Breeze Package (Optional)

```bash
composer remove laravel/breeze
```

## Post-Migration Testing

- [ ] Visit /auth/login and verify redirect to WorkOS
- [ ] Complete authentication and verify user creation
- [ ] Test logout functionality
- [ ] Test existing users can log in and are linked correctly

## Rollback Plan

If migration fails:
1. Restore database backup
2. Restore removed Breeze files from git
3. Remove WorkOS AuthKit: `composer remove workos/authkit-laravel`
4. Reinstall Breeze: `composer require laravel/breeze --dev && php artisan breeze:install`

---
*Generated by WorkOS AuthKit installer*
MARKDOWN;
    }

    #[\Override]
    public function getRiskLevel(): string
    {
        return 'Medium - Existing user authentication will change';
    }

    #[\Override]
    public function getSummary(): string
    {
        return 'Laravel Breeze';
    }

    private function detectBreezeStack(string $projectPath): string
    {
        if (File::exists($projectPath.'/resources/js/Pages')) {
            if (File::exists($projectPath.'/resources/js/app.tsx')) {
                return 'React + Inertia';
            }

            return 'Vue + Inertia';
        }

        if (File::exists($projectPath.'/resources/views/livewire')) {
            return 'Livewire';
        }

        return 'Blade';
    }

    private function listBreezeControllers(string $projectPath): string
    {
        $controllers = [
            'app/Http/Controllers/Auth/AuthenticatedSessionController.php',
            'app/Http/Controllers/Auth/ConfirmablePasswordController.php',
            'app/Http/Controllers/Auth/EmailVerificationNotificationController.php',
            'app/Http/Controllers/Auth/EmailVerificationPromptController.php',
            'app/Http/Controllers/Auth/NewPasswordController.php',
            'app/Http/Controllers/Auth/PasswordController.php',
            'app/Http/Controllers/Auth/PasswordResetLinkController.php',
            'app/Http/Controllers/Auth/RegisteredUserController.php',
            'app/Http/Controllers/Auth/VerifyEmailController.php',
        ];

        $existing = array_filter($controllers, fn ($c) => File::exists($projectPath.'/'.$c));

        if (empty($existing)) {
            return '- No Breeze controllers found';
        }

        return implode("\n", array_map(fn ($c) => "- `{$c}`", $existing));
    }

    private function listBreezeViews(string $projectPath): string
    {
        $viewPath = $projectPath.'/resources/views/auth';

        if (! File::isDirectory($viewPath)) {
            return '- No Breeze views found';
        }

        $files = File::files($viewPath);

        return implode("\n", array_map(fn ($f) => "- `resources/views/auth/{$f->getFilename()}`", $files));
    }
}
