<?php

declare(strict_types=1);

namespace WorkOS\AuthKit\Install\Plans;

use Illuminate\Support\Facades\File;

class FortifyMigrationPlan extends BaseMigrationPlan
{
    #[\Override]
    public function generate(string $projectPath): string
    {
        $features = $this->detectFortifyFeatures($projectPath);
        $databaseSection = $this->databaseMigrationSection();
        $envVarsSection = $this->envVarsSection();

        return <<<MARKDOWN
# Migration Plan: Laravel Fortify to WorkOS AuthKit

**Generated**: {$this->timestamp()}
**Risk Level**: {$this->getRiskLevel()}

## Overview

Laravel Fortify is a headless authentication backend. You likely have custom frontend views.

### Feature Mapping

| Fortify Feature | WorkOS Equivalent |
|-----------------|-------------------|
| Login | WorkOS AuthKit |
| Registration | WorkOS User Management |
| Password Reset | WorkOS Magic Link |
| Email Verification | WorkOS |
| Two-Factor Auth | WorkOS MFA |
| Password Confirmation | WorkOS Re-authentication |

{$this->detectedFeaturesSection($features)}

## Migration Steps

### Step 1: Database Changes

{$databaseSection}

### Step 2: Disable Fortify Features

In `config/fortify.php`, disable features that WorkOS will handle:

```php
'features' => [
    // Comment out or remove:
    // Features::registration(),
    // Features::resetPasswords(),
    // Features::emailVerification(),
    // Features::twoFactorAuthentication(),
],
```

### Step 3: Keep or Remove Fortify

**Option A: Remove entirely**
```bash
composer remove laravel/fortify
```

**Option B: Keep for non-auth features**
Keep Fortify if you use it for password confirmation in sensitive areas.

### Step 4: Update User Model

```php
use WorkOS\AuthKit\Models\Concerns\HasWorkOSId;
use WorkOS\AuthKit\Models\Concerns\HasWorkOSPermissions;

class User extends Authenticatable
{
    use HasWorkOSId;
    use HasWorkOSPermissions;
}
```

### Step 5: Update Routes

Remove Fortify auth routes, keep any custom routes.

WorkOS AuthKit provides routes at `/auth/*`:
- `/auth/login` - Redirects to WorkOS
- `/auth/callback` - Handles WorkOS callback
- `/auth/logout` - Logs out user

### Step 6: Update Views

Since Fortify is headless, you have custom views. Options:

**Option A: Remove custom views**
Remove your custom auth views and let WorkOS host the auth UI entirely.

**Option B: Keep login page as redirect**
Keep a simple login page that just redirects to `/auth/login`:

```php
// routes/web.php
Route::get('/login', fn () => redirect('/auth/login'))->name('login');
```

{$envVarsSection}

## Post-Migration Testing

- [ ] Visit /auth/login and verify redirect to WorkOS
- [ ] Complete authentication and verify user creation
- [ ] Test logout functionality
- [ ] Test existing users can log in and are linked correctly
- [ ] Verify any Fortify features you kept still work

## Rollback Plan

If migration fails:
1. Restore database backup
2. Remove WorkOS AuthKit: `composer remove workos/authkit-laravel`
3. Re-enable Fortify features in config

---
*Generated by WorkOS AuthKit installer*
MARKDOWN;
    }

    #[\Override]
    public function getRiskLevel(): string
    {
        return 'Medium - Fortify is headless, less to remove';
    }

    #[\Override]
    public function getSummary(): string
    {
        return 'Laravel Fortify';
    }

    /**
     * @return array<string, bool>
     */
    private function detectFortifyFeatures(string $projectPath): array
    {
        $features = [
            'registration' => false,
            'resetPasswords' => false,
            'emailVerification' => false,
            'twoFactorAuthentication' => false,
            'updateProfileInformation' => false,
            'updatePasswords' => false,
        ];

        $configPath = $projectPath.'/config/fortify.php';
        if (! File::exists($configPath)) {
            return $features;
        }

        $contents = File::get($configPath);

        foreach (array_keys($features) as $feature) {
            if (str_contains($contents, "Features::{$feature}")) {
                $features[$feature] = true;
            }
        }

        return $features;
    }

    /**
     * @param  array<string, bool>  $features
     */
    private function detectedFeaturesSection(array $features): string
    {
        $enabledFeatures = array_keys(array_filter($features));

        if (empty($enabledFeatures)) {
            return '';
        }

        $featureList = implode("\n", array_map(fn ($f) => "- {$this->formatFeatureName($f)}", $enabledFeatures));

        return <<<MARKDOWN

## Detected Fortify Features

The following Fortify features are enabled in your configuration:

{$featureList}

These features will be replaced by WorkOS AuthKit functionality.
MARKDOWN;
    }

    private function formatFeatureName(string $feature): string
    {
        return match ($feature) {
            'registration' => 'User Registration',
            'resetPasswords' => 'Password Reset',
            'emailVerification' => 'Email Verification',
            'twoFactorAuthentication' => 'Two-Factor Authentication',
            'updateProfileInformation' => 'Profile Information Updates',
            'updatePasswords' => 'Password Updates',
            default => $feature,
        };
    }
}
