<?php

declare(strict_types=1);

namespace WorkOS\AuthKit\Install\Plans;

use Illuminate\Support\Facades\File;

class JetstreamMigrationPlan extends BaseMigrationPlan
{
    public function generate(string $projectPath): string
    {
        $hasTeams = $this->detectTeamsFeature($projectPath);
        $hasApiTokens = $this->detectApiTokensFeature($projectPath);
        $databaseSection = $this->databaseMigrationSection();
        $envVarsSection = $this->envVarsSection();

        return <<<MARKDOWN
# Migration Plan: Laravel Jetstream to WorkOS AuthKit

**Generated**: {$this->timestamp()}
**Teams Feature**: {$this->enabledDisabled($hasTeams)}
**API Tokens Feature**: {$this->enabledDisabled($hasApiTokens)}
**Risk Level**: {$this->getRiskLevel()}

## Overview

You're migrating from Laravel Jetstream to WorkOS AuthKit. Jetstream is a more comprehensive starter kit with features beyond basic authentication.

### Feature Mapping

| Jetstream Feature | WorkOS Equivalent | Notes |
|-------------------|-------------------|-------|
| Login/Register | WorkOS AuthKit | Full replacement |
| Password Reset | WorkOS Magic Link | Handled by WorkOS |
| Email Verification | Not needed | WorkOS verifies emails |
| Two-Factor Auth | WorkOS MFA | Configure in WorkOS Dashboard |
| Profile Management | Custom | Build your own profile page |
| API Tokens | Sanctum (keep) | See guidance below |
| Teams | Custom | See guidance below |

{$this->teamsGuidance($hasTeams)}

{$this->apiTokensGuidance($hasApiTokens)}

## Step-by-Step Migration

### Step 1: Database Changes

{$databaseSection}

### Step 2: Update User Model

```php
use WorkOS\AuthKit\Models\Concerns\HasWorkOSId;
use WorkOS\AuthKit\Models\Concerns\HasWorkOSPermissions;

class User extends Authenticatable
{
    use HasWorkOSId;
    use HasWorkOSPermissions;
    // Keep other Jetstream traits if needed (HasApiTokens, HasTeams)
}
```

### Step 3: Route Changes

Keep profile routes if you want custom profile management.
Remove auth routes - WorkOS AuthKit provides `/auth/*`.

### Step 4: View Changes

Keep profile views if customized.
Remove auth views - WorkOS hosts the auth UI.

## Risk Considerations

- **High complexity** if using Teams feature
- **Medium complexity** if using API tokens
- **Low complexity** if basic Jetstream without Teams/API tokens

{$envVarsSection}

## Post-Migration Testing

- [ ] Visit /auth/login and verify redirect to WorkOS
- [ ] Complete authentication and verify user creation
- [ ] Test logout functionality
- [ ] Test existing users can log in and are linked correctly
{$this->teamsTestingChecklist($hasTeams)}
{$this->apiTokensTestingChecklist($hasApiTokens)}

## Rollback Plan

If migration fails:
1. Restore database backup
2. Restore removed Jetstream files from git
3. Remove WorkOS AuthKit: `composer remove workos/authkit-laravel`

---
*Generated by WorkOS AuthKit installer*
MARKDOWN;
    }

    public function getRiskLevel(): string
    {
        return 'High - Jetstream has many integrated features';
    }

    public function getSummary(): string
    {
        return 'Laravel Jetstream';
    }

    private function detectTeamsFeature(string $projectPath): bool
    {
        if (File::exists($projectPath.'/app/Models/Team.php')) {
            return true;
        }

        $configPath = $projectPath.'/config/jetstream.php';
        if (File::exists($configPath)) {
            $contents = File::get($configPath);
            if (str_contains($contents, 'Features::teams')) {
                return true;
            }
        }

        return false;
    }

    private function detectApiTokensFeature(string $projectPath): bool
    {
        $configPath = $projectPath.'/config/jetstream.php';
        if (File::exists($configPath)) {
            $contents = File::get($configPath);
            if (str_contains($contents, 'Features::api')) {
                return true;
            }
        }

        $userPath = $projectPath.'/app/Models/User.php';
        if (File::exists($userPath)) {
            $contents = File::get($userPath);
            if (str_contains($contents, 'HasApiTokens')) {
                return true;
            }
        }

        return false;
    }

    private function teamsGuidance(bool $hasTeams): string
    {
        if (! $hasTeams) {
            return '';
        }

        return <<<'MARKDOWN'

## Teams Feature Guidance

Your Jetstream installation uses the Teams feature. WorkOS AuthKit doesn't directly replace team functionality, but you have options:

### Option 1: Keep Jetstream Teams
Keep the Teams model and relationships. WorkOS handles authentication, Jetstream handles teams.

```php
// User model keeps HasTeams trait
class User extends Authenticatable
{
    use HasWorkOSId;
    use HasTeams; // Keep this
}
```

### Option 2: Use WorkOS Organizations
WorkOS supports organizations for team-like functionality with enterprise SSO per organization. This requires more significant changes but provides enterprise-grade team management.

See: https://workos.com/docs/user-management/organizations

### Option 3: Build Custom Teams
If you only need basic team functionality, consider building a simpler custom solution that integrates better with WorkOS user management.

MARKDOWN;
    }

    private function apiTokensGuidance(bool $hasApiTokens): string
    {
        if (! $hasApiTokens) {
            return '';
        }

        return <<<'MARKDOWN'

## API Tokens Guidance

Your Jetstream installation uses API Tokens (Laravel Sanctum). This feature is separate from authentication and can be kept.

### Recommended Approach

Keep Laravel Sanctum for API token management:

```php
// User model keeps HasApiTokens trait
class User extends Authenticatable
{
    use HasWorkOSId;
    use HasApiTokens; // Keep this
}
```

The token management UI in Jetstream can remain - it's independent of how users authenticate.

MARKDOWN;
    }

    private function teamsTestingChecklist(bool $hasTeams): string
    {
        if (! $hasTeams) {
            return '';
        }

        return <<<'MARKDOWN'
- [ ] Verify team creation still works
- [ ] Verify team switching still works
- [ ] Verify team member invitations work
MARKDOWN;
    }

    private function apiTokensTestingChecklist(bool $hasApiTokens): string
    {
        if (! $hasApiTokens) {
            return '';
        }

        return <<<'MARKDOWN'
- [ ] Verify API token creation still works
- [ ] Verify API authentication with tokens still works
MARKDOWN;
    }
}
